# main.yml - Sets up a glusterfs file server node
---

- name: add centos gluster3.8 repo
  command: echo $'[centos-gluster38]\nname=CentOS-$releasever - Gluster 3.8\nbaseurl=http://mirror.centos.org/centos/$releasever/storage/$basearch/gluster-3.8/\ngpgcheck=1\nenabled=1\ngpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Storage' | sudo tee /etc/yum.repos.d/gluster38.repo

- name: yum update
  command: yum -y update
- name: Install required packages
  yum:
    name: centos-release-gluster38
    state: latest
  when: not custom_repo

- name: Install required packages
  yum:
    name: glusterfs-server-3.8.4
    state: latest

- name: Enable gluster server
  service:
    name: glusterd
    enabled: yes
    state: started

- name: Open ports
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - 111
    - "24007:24008"
    - "49152:49154"
  when: iptables_config

- name: Save iptables config
  command: "/sbin/service iptables save"
  notify:
    - restart iptables
  when: iptables_config
